name: Rust

on:
  push:
    branches: [ "rq" ]
  pull_request:
    branches: [ "rq" ]

env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: nightly
        override: true
        profile: minimal
        components: rustfmt
    - name: musl build release
      run: cargo +nightly b -r --target $BUILD_TARGET
